### ISSUE TITLE
several testing failures on master

### ISSUE THREAD

**Issue by xixilive** [jrsearles/SandBoxr#3] opened 2015-12-11 07:45 UTC
Case1:  https://github.com/jrsearles/SandBoxr/blob/master/test/json.tests.js#L18

```
// use Date.UTC maybe a approach
runner.confirmBlock("JSON.stringify(new Date(2000,1,1))=='\"2000-02-01T05:00:00.000Z\"';", done);
```

Case2: https://github.com/jrsearles/SandBoxr/blob/master/test/type-number.tests.js#L28

```
runner.confirmBlock("1 == new Number(1);", done);
```

Case3: https://github.com/jrsearles/SandBoxr/blob/master/test/type-string.tests.js#L138

```
runner.confirmBlock("new String('foo') == 'foo';");
```

**Comment by jrsearles** [comment] 2015-12-16 17:10
Thanks - i have noticed the two implicit comparison tests failing in some environments but whenever i've debugged it i've been unable to reproduce it.

You're right, the other test might just be a flaw in test. Most of the date code just wraps the host environments date methods.

I hope to have another release coming up within a week or so and will try to address all of these issues by then.

**Comment by jrsearles** [comment] 2016-01-03 05:34
Failure 2 & 3 were related to another test that was overwriting the implicit equals operator. It was replacing it globally, which was affecting the tests.

I rewrote the test in case 1 so it shouldn't be as sensitive to environment differences.

These have been merged into master, though i have not created a release yet.

**Comment by jrsearles** [comment] 2016-01-11 01:10
These should be fixed now. Let me now if you still have any issues with the tests.

**Closed as completed by jrsearles** 2016-01-11 01:10 UTC
Labels: bug

**Comment by xixilive** [comment] 2016-01-11 02:57
:+1:
